name: "jobs"

on: push

defaults:
    run:
        working-directory: my-app

env:
    NODE_VERSION: 16.x

jobs:
    lint:
        runs-on: ubuntu-latest

        name: Lint changed files

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}

            - name: Install dependencies
              run: npm install
            
            - name: Get changed files
              id: changed-js-files
              uses: ./.github/actions/changed-files
              with:
                files: |
                    **/*.js
            
            - name: Check changed files with ESLint
              run: |
                TO_LINT=""
                for file in ${{ steps.changed-js-files.outputs.all_changed_files }}; do
                    TO_LINT+=$(echo ${file#*/})
                done
                npm run lint $TO_LINT